### ISSUE TITLE
Godot 3.0 compatibility

### ISSUE THREAD

**Issue by takhimi** [kloder-games/godot-admob#14]
Is this compatible with Godot 3.0 ? If not , can you update it so that it is compatible with godot 3.0.

**Comment by Shin-NiL** [comment]
I'm not sure about Android, but the iOS module will not work on 3.0.

**Comment by de11ed** [comment]
Any news/ updates on this?

**Comment by Shin-NiL** [comment]
AFAIK the Android module will work with minimal changes on the project side only, ie:

Changing 
```
Globals.has_singleton("AdMob")
Globals.get_singleton("AdMob")
```
to
```
Engine.has_singleton("AdMob")
Engine.get_singleton("AdMob")
```
and adding the lines
```
[android]
modules="org/godotengine/godot/GodotAdMob"
```
into `project.godot` file instead of `engine.cfg`


The iOS module will not work as is, but I've no plans to touch it until Godot 3.1. Maybe someone else can contribute.

**Comment by de11ed** [comment]
Alright, I see! I wish I could contribute but I have zero knowledge about this.

**Comment by de11ed** [comment]
I managed to get it to compile with Scons by changing some lines here and there. But since I have never recompiled the engine before with custom modules I don't know if I made a mistake somewhere or if I screwed up the code in the game, because it's now showing any ad when I play the test file. I don't know if you've tried or how far you've gotten when trying to compile for iOS but if you recon it should work after getting it to compile with Scons then I will post my findings tomorrow, when I'm at a mac.

**Comment by Shin-NiL** [comment]
@de11ed could you or someone else test [my branch](https://github.com/Shin-NiL/godot-admob/tree/godot-3) on a real device? I have no idea if it's working or not because I don't have an iPhone to test it :(

**Comment by de11ed** [comment]
Awesome! I'll try it at some point today and get back to you.

**Comment by de11ed** [comment]
Awesome @Shin-NiL ! It's working on iOS too! :D This is great news! Thank you so much!

**Comment by Shin-NiL** [comment]
Thank you very much for testing @de11ed , I'll create a pull request to the main repository later today.

**Comment by de11ed** [comment]
Hmmm. It seems though as the video reward isn't loading. I was a little hasty before and just thought the video hadn't fully loaded yet. But upon further investigation it seems as it's not loading properly.

This is the error logg I get in Xcode:

```
<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
2018-03-13 13:21:11.036448+0100 iosTest[1412:691027] Reward based video ad failed to load: No ad returned from any ad server.
```

I tried setting the -ObjC in the settings but that didn't change anything. I also tried changing the ID to the one they advise to use on their website when trying reward videos.

**Comment by Shin-NiL** [comment]
I see, rewarded videos are a little tricky to test. Are you using true or false in the `isReal` parameter? I don't believe it's a linking error because the Banner and Interstitial uses the same framework. 

The `No ad returned from any ad server` seem to be a recurring and snatchy error. Are you using Wifi? 

Can you tell me if interstitial are working?

**Comment by de11ed** [comment]
Yeah, I don't think so either. The `isReal`is set to false. 

Using Wifi yes.

Yes, the banner and interstitial is working flawlessly.

**Comment by Shin-NiL** [comment]
I think you can find the solution here: https://github.com/kloder-games/godot-admob/issues/13

> So the issue that I was having was because I had "Limit Ad Tracking" enabled on my iPhone. Going into Settings -> Privacy -> Advertising and disabling Limit Ad Tracking allowed the rewarded ads to load.
> 
> In short the issue was purely on my end - however it does make me wonder how I could effectively implement rewarded ads when not all users would have this setting disabled

Thanks @mkamener

**Comment by de11ed** [comment]
Aha! That solved it, now it works! Like he said, now I just gotta figure out how I should go about it since I think almost everyone has that setting enabled.
Thank you @Shin-NiL and @mkamener

**Comment by Shin-NiL** [comment]
Nice! Thanks again for testing ;)

**Comment by tomnahooy** [comment]
Hi, I've tried @Shin-NiL 's branch as well, but I can't get XCode to build the example project. Here's what I get:
![screen shot 2018-03-15 at 10 03 14](https://user-images.githubusercontent.com/11715776/37453510-25ed7fa0-2838-11e8-918c-fc55144242f4.png)

I tried following the instructions on the readme, but they seem incompatible with 3.0(.2). So here's what I did:

compiled debug and release for both 64- and 32-bit --> create fat binaries for 64 and 32-bit --> put them in  ~/Library/Application Support/Godot/templates/3.0.2.stable/iphone, replacing the fat binaries there for the ones I just created (with the exact same name) --> compress again to iphone.zip

I export via the editor's ios exporter directly, because the xcodeproject in the iphone.zip template can't be opened.

Can you tell me what I'm missing? Thanks!

**Comment by Shin-NiL** [comment]
What scons commands did you use to compile the module?
As I don't have an iPhone I can't tell you exactly the procedure :(

Hey @de11ed , can you describe to us how did you compile and run your project?

**Comment by tomnahooy** [comment]
The exact ones I used are:

`scons p=iphone  verbose=no tools=no arch=arm64 target=release_debug`
`scons p=iphone  verbose=no tools=no arch=arm64 target=release`

and for 32-bit:
`scons p=iphone verbose=no tools=no arch=armv7 target=release_debug`
`scons p=iphone verbose=no tools=no arch=armv7 target=release`

**Comment by Shin-NiL** [comment]
Well, I'm having similar issue on simulator.

**Comment by de11ed** [comment]
Ah yes! I had to add the GoogleMobileAds.framwork manually in xcode into the project, using the link binary with libraries, click the plus sign and then "Add other...". Make sure that the framework is in the same folder as the xcode project. And also add these frameworks: StoreKit, GameKit, CoreVideo, AdSupport, MessageUI, CoreTelephony, CFNetwork and MobileCoreServices. Let me know if that helped.

**Comment by tomnahooy** [comment]
Yes! That did it! Thanks a million @de11ed and @Shin-NiL !

**Comment by Shin-NiL** [comment]
Thanks @de11ed I think something has changed in the linking process for Godot 3. I'll investigate this.
