### ISSUE TITLE
My real ads are not working

### ISSUE THREAD

**Issue by Felipe634** [kloder-games/godot-admob#156]
**OS target (Android/iOS):**
IOS

**Godot version:**
3.2.3

**Issue description:**
My test ads were working perfectly and how I want them to but the real ads aren’t working in my game and i know this as I asked my friends to see if it worked. But I am still getting ad requests from admob. Do you have any idea why it’s not working?

**Comment by gumaciel** [comment]
If your account is new, it take some time to appear real ads.

You can try on the new AdMob plugin that I developed: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS

**Comment by Felipe634** [comment]
My admob account was created in june/july so I dont think that is the problem and the ads for android are working perfectly. Is there anything else I can do?

**Comment by gumaciel** [comment]
Hmmm I don't know, how are you using this module for Android on 3.2.3? Should not work

**Comment by Felipe634** [comment]
It is a new module apparently and its only for android, with some plugin downloads you can make an admob node in godot and set the ads from there. For this IOS module should I initialize the ads with content rating or just normally because maybe that is the issue.

**Comment by gumaciel** [comment]
This module repository doesn't use all the parameters in iOS, the only parameters that use are "is_real" and "instance_id":

   [banner initialize :isReal :instanceId];

If you want a plugin that are compatible with the newest versions of Godot in iOS and Android without change the logic of code, check this module here: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS

**Comment by gumaciel** [comment]
But probably the ads are not appearing using kloder because in some way you din't configure right the plugin for iOS, and on Shin Nil Android is appearing because is different plugins and well configurated

**Comment by Felipe634** [comment]
So what are you recommending I do for this to work?

**Comment by gumaciel** [comment]
I recommend you to use this plugin: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS 

The plugin is already compiled for iOS and Android and it's very easy to use:

iOS: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/tag/iOS_v3.0%2B

Android: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/tag/Android_v3.2.2%2B


There's a exported example working for Android, but for iOS you still need to configure on XCode: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/actions/runs/404973311

You need to download on Artifact, if you have some difficult you can chat with me on Discord: gustavottc#5069 or open a issue on the repository.

I will close the issue because it should work on real ids, this repository always worked with real ids on iOS and Android < 3.2 (only if this doesn't work on new Godot versions but I don't think so)
