### ISSUE TITLE
Issues with screen orientation

### ISSUE THREAD

**Issue by ghost** [kloder-games/godot-admob#31]
OS target (Android/iOS): Android

Godot version: 2.1.4 / 2.1.5

Issue description: Is there a way to rotate the way ads are displayed? My app was build for landscape, which Godot defaults to, however it's actually meant to be played as portrait, which means that banners are displayed at the right corner, which is the screen's landscape "top", interstitials are further cropped, pixelated and off screen boundaries. This is also how the provided sample projects are set up.

Is there a way to fake the screen orientation, as in having an API function that does so? Or having an API function that fakes where the top or bottom of the screen is?

**Comment by Shin-NiL** [comment]
Why can't you set your app as portrait?

**Comment by hasherkeen** [comment]
It's a board game, and makes heavy use of screen dimensions to calculate positions and scales. Simply setting it to portrait deranges all the icons in the screen.

I've been trying to port it however, rotating the menus was easy, everything else that is programmatically and mathematically generated, positioned and manipulated is a headache. 

This is very much my first app, and in all honesty i thought Godot's default landscape was the right way to go for Android. Never came to my mind 6 months later at the final step of adding ads would prove such decision to have been such a colossal mistake.

**Comment by Shin-NiL** [comment]
I'm sorry but I'm afraid I'm not understanding. I have published games using both orientations and I had no issue with this module.

**Comment by hasherkeen** [comment]
I understand, i did not know of these concepts prior to making the game, this is indeed a beginner's mistake.

When the game is exported landscaped the x axis is the top of the screen, so a banner set with isTop shows on the right side of the screen. When the game is exported as portrait banners are displayed correctly, intertitials and videos so too, however menus are pinched and squeezed (scaled) to the screen as they suffer a 90 degrees rotation.

If you don't mind me kindly asking this here if there's any acceptable workaround this (e.g. an option to rotate the viewport), since this is no longer an issue related to this admob library but rather a mistake of mine.

**Comment by Shin-NiL** [comment]
It's really sad :(

I don't know if there is a easy workaround, but your best shot is to ask in one of the official Godot Engine communication channels, maybe someone with more knowledge about the subject can help you.

**Comment by hasherkeen** [comment]
Alrighty! Thank you and also to kodler-games for releasing this addon to the public !
