### ISSUE TITLE
godot admob module showing none targeted ads .

### ISSUE THREAD

**Issue by MrZak-dev** [kloder-games/godot-admob#68]
I have been working with this module for 4 months, and one of the things that i realized that admob ads in godot games are **less targeted**  ( it has no relation with the user) than the ads if you use android studio .
any idea about this problem ?

**Comment by Shin-NiL** [comment]
Because with Android Studio you're working with Java or Kotlin, which have full access to the Admob API, including the targeting functions.
 
This module only exposes to GDScript the functions that were manually mapped in the code, so not all functions are available. Only the methods and functions implemented by the module's developers are present, but anyone can add more to make it more complete.
