### ISSUE TITLE
Combine Modules - PreCompiled Apk Features

### ISSUE THREAD

**Issue by vini-guerrero** [kloder-games/godot-admob#82]
**OS target (Android/iOS):**
Android

**Godot version:**
3.1.1

**Issue description:**
Not really an issue but a doubt. Would it be possible to follow the same patterns you did on this module adding an external library without a re-compile dependency (pre-compiled apks work very well) to the same for Google Play Game Services?
I found these examples ( https://github.com/playgameservices/android-basic-samples/tree/master/CollectAllTheStars2/src/main/res/values ) and I was wondering if it would be possible to combine with this module and have both features.
Thanks in advance @Shin-NiL !

**Comment by Shin-NiL** [comment]
The problem with Google Play Game Services is that your app id must be in a xml resource. This way the APK must be packaged again. 
[The upcoming new android plugin system](https://godotengine.org/article/godot-3-2-will-get-new-android-plugin-system) will make our lives much easier there as will be no need to recompile the template anymore since the editor will be able to assemble the APK.

**Comment by vini-guerrero** [comment]
Awesome, thanks for the tips! I was planning to use their restfull API for google game services, but the have deprecated it....
