### ISSUE TITLE
Doesn't work with real ads

### ISSUE THREAD

**Issue by sntdevco** [kloder-games/godot-admob#96]
**OS target (Android/iOS):** Android
**Godot version:** 3.1.1

**Issue description:**
When `isReal` is set to `true` the ad no longer loads. I am using the pre-compiled template from @Shin-NiL's repository. I expect the ads to appear when in real-world mode, I'm also using the placements from my AdMob App (with my account), but no ads are served, I can confirm that the account is active as I can serve ads when using a normal Android Studio project. Also, test ads worked perfectly, then why not real ads? I've already waited 96 hours, and no change yet, although I can serve ads in my other apps. Any help is appreciated

**Comment by wombatwingdings** [comment]
Try it in a "release" build rather than "debug". I think I had the same issue in debug, but was ok in release.

**Comment by Shin-NiL** [comment]
Please paste your logcat output here, as descripted in the readme file.

**Comment by sntdevco** [comment]
I'm using a release build. It doesn't work. I'll paste the logcat output as soon as possible
________________________________

**Comment by takhimi** [comment]
I have the same problem. Test ads works great, but when set isReal to true, there are no ads served. Tested with released apk.

**Comment by Shin-NiL** [comment]
Where are you from? Admob's fill rate is poor in some countries.

**Comment by takhimi** [comment]
@Shin-NiL Whoopss. I'm from Malaysia. It is now ok. Turns out google blocked my ads before the dateline that they gave me. I have to submit for request for a review. Now everything is working fine. 

The game is here https://play.google.com/store/apps/details?id=com.gmart.munchiebob (shameful promoting my game. Sorry)

I have to port this game from construct 2 to Godot. Since construct 2 exporting to android pretty much dead(CocoonIO,Intel XDK) , I had to use other game engine to do this. Thank you guys for giving me a little bit of hope..

**Comment by Shin-NiL** [comment]
Nice to know it's working @takhimi.
It' not a shame to show your game, one of the most grateful thing for sharing my code is to see it in action ;)

**Comment by sntdevco** [comment]
Hey there, the ads still don't appear in my game. I got rewarded ads working on a normal Android Studio project, but getting it to work using this module have been failed attempts. I wonder why test ads work so easily, but normal ads don't serve at all. @takhimi Can you share your experience on how you got it to work?

**Comment by takhimi** [comment]
@sntdevco I think if it is new app or new game, it might take few days to show real ads after it is published. For my case it is an old game(using construc 2) but the ads is disabled by google because it does not comply with admob policy. So I make changes using godot and published the game. After that I need to submit for a review to see if it does comply or not. If it is ok, they will enable the ads back.

**Comment by sntdevco** [comment]
@takhimi Nothing like that. It works perfectly in a normal Android app (built with Android Studio)

**Comment by sntdevco** [comment]
Closing since there has been no response
